llms:
  github:
    gpt-4o-mini:
      model_name: gpt-4o-mini
      max_tokens: 4096
      frequency_penalty: 0.1  # not in used
      presence_penalty: 0.1  # not in used
    gpt-4o:
      model_name: gpt-4o
      max_tokens: 4096
      frequency_penalty: 0.1  # not in used
      presence_penalty: 0.1  # not in used
  yi-01:
    yi-large:
      model_name: yi-large-fc
      max_tokens: 1024
      frequency_penalty: 0.1  # not in used
      presence_penalty: 0.1  # not in used
      currency: RMB
      input_price: 20
      output_price: 20
    yi-large-turbo:
      model_name: yi-large-turbo
      max_tokens: 1024
      frequency_penalty: 0.1  # not in used
      presence_penalty: 0.1  # not in used
      currency: RMB
      input_price: 12
      output_price: 12
    yi-spark:
      model_name: yi-spark
      max_tokens: 1024
      frequency_penalty: 0.1  # not in used
      presence_penalty: 0.1  # not in used
      currency: RMB
      input_price: 1
      output_price: 11
chains:
  intent: # heavy
    # llm: yi-large
    llm: gpt-4o
    temperature: 0.01
    top_p: 0.95
  chitchat: # light
    # llm: yi-large-turbo
    llm: gpt-4o-mini
    temperature: 0.5
    top_p: 0.95
  cusine: # heavy
    # llm: yi-large
    llm: gpt-4o
    temperature: 0.5
    top_p: 0.95
    no_of_cusine: 3
  intro: # light
    # llm: yi-large-turbo
    llm: gpt-4o-mini
    temperature: 0.1
    top_p: 0.95
  need_for_recipe: # light
    # llm: yi-large-turbo
    llm: gpt-4o-mini
    temperature: 0.5
    top_p: 0.95
  need_for_other_help: # heavy
    # llm: yi-large
    llm: gpt-4o
    temperature: 0.5
    top_p: 0.95
  write_recipe: # heavy
    # llm: yi-large
    llm: gpt-4o
    temperature: 0.1
    top_p: 0.95